services:
  middleware:
    build: ./middleware
    container_name: borsa_middleware
    ports:
      - "5001:5001"
    environment:
      - PERFORMANCE_TEST=false
    volumes:
      - ./output_logs:/app/output_logs

  data_generator:
    build: ./data_generator
    container_name: borsa_generator
    depends_on:
      - middleware